[package]
name = "aether-config"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aether-core = { path = "../aether-core" }
serde.workspace = true
serde_yaml.workspace = true
anyhow.workspace = true
tracing.workspace = true
